# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_download_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoDownloadDialog(object):
    def setupUi(self, VideoDownloadDialog):
        VideoDownloadDialog.setObjectName("VideoDownloadDialog")
        VideoDownloadDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        VideoDownloadDialog.resize(588, 165)
        VideoDownloadDialog.setMaximumSize(QtCore.QSize(16777215, 165))
        self.gridLayout = QtWidgets.QGridLayout(VideoDownloadDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_top = QtWidgets.QGridLayout()
        self.gridLayout_top.setObjectName("gridLayout_top")
        self.lineEditUrl = QtWidgets.QLineEdit(VideoDownloadDialog)
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.gridLayout_top.addWidget(self.lineEditUrl, 0, 2, 1, 2)
        self.labelName = QtWidgets.QLabel(VideoDownloadDialog)
        self.labelName.setMinimumSize(QtCore.QSize(0, 23))
        self.labelName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelName.setObjectName("labelName")
        self.gridLayout_top.addWidget(self.labelName, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(VideoDownloadDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_top.addWidget(self.progressBar, 4, 0, 1, 4)
        self.labelUrl = QtWidgets.QLabel(VideoDownloadDialog)
        self.labelUrl.setMinimumSize(QtCore.QSize(0, 23))
        self.labelUrl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelUrl.setObjectName("labelUrl")
        self.gridLayout_top.addWidget(self.labelUrl, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_top.addItem(spacerItem, 3, 0, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(VideoDownloadDialog)
        self.lineEditName.setObjectName("lineEditName")
        self.gridLayout_top.addWidget(self.lineEditName, 1, 2, 1, 1)
        self.pushButtonName = QtWidgets.QPushButton(VideoDownloadDialog)
        self.pushButtonName.setMinimumSize(QtCore.QSize(32, 23))
        self.pushButtonName.setMaximumSize(QtCore.QSize(32, 16777215))
        self.pushButtonName.setObjectName("pushButtonName")
        self.gridLayout_top.addWidget(self.pushButtonName, 1, 3, 1, 1)
        self.labelOutdir = QtWidgets.QLabel(VideoDownloadDialog)
        self.labelOutdir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOutdir.setObjectName("labelOutdir")
        self.gridLayout_top.addWidget(self.labelOutdir, 2, 0, 1, 1)
        self.lineEditOutdir = QtWidgets.QLineEdit(VideoDownloadDialog)
        self.lineEditOutdir.setObjectName("lineEditOutdir")
        self.gridLayout_top.addWidget(self.lineEditOutdir, 2, 2, 1, 1)
        self.pushButtonOutdir = QtWidgets.QPushButton(VideoDownloadDialog)
        self.pushButtonOutdir.setMinimumSize(QtCore.QSize(32, 23))
        self.pushButtonOutdir.setMaximumSize(QtCore.QSize(32, 16777215))
        self.pushButtonOutdir.setObjectName("pushButtonOutdir")
        self.gridLayout_top.addWidget(self.pushButtonOutdir, 2, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_top, 1, 0, 1, 1)
        self.gridLayout_bottom = QtWidgets.QGridLayout()
        self.gridLayout_bottom.setObjectName("gridLayout_bottom")
        self.pushButtonCancel = QtWidgets.QPushButton(VideoDownloadDialog)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_bottom.addWidget(self.pushButtonCancel, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_bottom.addItem(spacerItem1, 0, 2, 1, 1)
        self.pushButtonDownload = QtWidgets.QPushButton(VideoDownloadDialog)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.gridLayout_bottom.addWidget(self.pushButtonDownload, 0, 3, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(VideoDownloadDialog)
        self.pushButtonStop.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout_bottom.addWidget(self.pushButtonStop, 0, 4, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_bottom, 2, 0, 1, 1)

        self.retranslateUi(VideoDownloadDialog)
        QtCore.QMetaObject.connectSlotsByName(VideoDownloadDialog)

    def retranslateUi(self, VideoDownloadDialog):
        _translate = QtCore.QCoreApplication.translate
        VideoDownloadDialog.setWindowTitle(_translate("VideoDownloadDialog", "Download Video"))
        self.labelName.setText(_translate("VideoDownloadDialog", "Name"))
        self.labelUrl.setText(_translate("VideoDownloadDialog", "Url"))
        self.pushButtonName.setText(_translate("VideoDownloadDialog", "..."))
        self.labelOutdir.setText(_translate("VideoDownloadDialog", "Folder"))
        self.pushButtonOutdir.setText(_translate("VideoDownloadDialog", "..."))
        self.pushButtonCancel.setText(_translate("VideoDownloadDialog", "Cancel"))
        self.pushButtonDownload.setText(_translate("VideoDownloadDialog", "Download"))
        self.pushButtonStop.setText(_translate("VideoDownloadDialog", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoDownloadDialog = QtWidgets.QDialog()
    ui = Ui_VideoDownloadDialog()
    ui.setupUi(VideoDownloadDialog)
    VideoDownloadDialog.show()
    sys.exit(app.exec_())
